swagger: '2.0'
securityDefinitions:
  test:
    type: oauth2
    authorizationUrl: "data:text/html,<script>alert('OAuth XSS')</script>"
info:
  version: "1.0.0"
  title: "Swagger XSS Test"
  description: <math xlink:href="jaVasCript:/*-/*`/*\`/*&#039;/*&quot;/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//&lt;/stYle/&lt;/titLe/&lt;/teXtarEa/&lt;/scRipt/--!&gt;\x3csVg/&lt;sVg/oNloAd=alert()//&gt;\x3e">click me</math>
paths:
  /test:
    get:
      responses:
        200:
          description: "Test if Swagger UI executes any payloads."
